-- begin TELEGRAMBOT_NOTE
alter table TELEGRAMBOT_NOTE add constraint FK_TELEGRAMBOT_NOTE_ON_CHAT foreign key (CHAT_ID) references TELEGRAMBOT_CHAT(ID)^
create index IDX_TELEGRAMBOT_NOTE_ON_CHAT on TELEGRAMBOT_NOTE (CHAT_ID)^
-- end TELEGRAMBOT_NOTE
-- begin TELEGRAMBOT_FILE_DESCRIPTOR_LINK
alter table TELEGRAMBOT_FILE_DESCRIPTOR_LINK add constraint FK_FILDES_ON_NOTE foreign key (NOTE_ID) references TELEGRAMBOT_NOTE(ID)^
alter table TELEGRAMBOT_FILE_DESCRIPTOR_LINK add constraint FK_FILDES_ON_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID)^
-- end TELEGRAMBOT_FILE_DESCRIPTOR_LINK

-- begin TELEGRAMBOT_CATEGORY
create unique index IDX_TELEGRAMBOT_CATEGORY_UK_NAME on TELEGRAMBOT_CATEGORY (NAME) where DELETE_TS is null ^
-- end TELEGRAMBOT_CATEGORY
-- begin TELEGRAMBOT_NOTE_CATEGORIES
alter table TELEGRAMBOT_NOTE_categories add constraint FK_NOTCAT_ON_NOTE foreign key (note_ID) references TELEGRAMBOT_NOTE(ID)^
alter table TELEGRAMBOT_NOTE_categories add constraint FK_NOTCAT_ON_CATEGORY foreign key (categories_ID) references TELEGRAMBOT_CATEGORY(ID)^
-- end TELEGRAMBOT_NOTE_CATEGORIES
-- begin TELEGRAMBOT_FILE_DESCRIPTOR_CHAT_LINK
alter table TELEGRAMBOT_FILE_DESCRIPTOR_CHAT_LINK add constraint FK_FILDESCHA_ON_CHAT foreign key (CHAT_ID) references TELEGRAMBOT_CHAT(ID)^
alter table TELEGRAMBOT_FILE_DESCRIPTOR_CHAT_LINK add constraint FK_FILDESCHA_ON_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID)^
-- end TELEGRAMBOT_FILE_DESCRIPTOR_CHAT_LINK
-- begin TELEGRAMBOT_TELEGRAM_USER
create unique index IDX_TELEGRAMBOT_TELEGRAM_USER_UK_USER_ID on TELEGRAMBOT_TELEGRAM_USER (USER_ID) where DELETE_TS is null ^
-- end TELEGRAMBOT_TELEGRAM_USER
